### ISSUE TITLE
GenType Shims

### ISSUE THREAD

**Issue by mx-rd** [rescript-lang/std#2]
I currently came across [this issue](https://forum.rescript-lang.org/t/referencing-standard-types-in-ts-gentype/4010) in writing a library for use in js, using `@rescript/std` as described in the manual. I think it would be *very* handy, if `@rescript/std` could include and somehow expose the shims. That was actually my expectation going in.

Would that be possible?

**Comment by cknitt** [comment]
This repo is obsolete and will be archived.

If still relevant, please open an issue on the rescript-compiler repo.
